# Generated by Django 5.0.2 on 2025-03-25 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名字')),
                ('breed', models.CharField(max_length=100, verbose_name='品种')),
                ('height', models.FloatField(verbose_name='身高(cm)')),
                ('weight', models.FloatField(verbose_name='体重(kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '狗狗',
                'verbose_name_plural': '狗狗',
                'ordering': ['-created_at'],
            },
        ),
    ]
