# Generated by Django 5.0.2 on 2025-03-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dogs/', verbose_name='狗狗图片'),
        ),
    ]
