# Generated by Django 5.0.2 on 2025-03-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STM32Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='主题')),
                ('payload', models.TextField(verbose_name='数据内容')),
                ('qos', models.IntegerField(default=0, verbose_name='服务质量')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
            ],
            options={
                'verbose_name': 'STM32数据',
                'verbose_name_plural': 'STM32数据',
                'ordering': ['-timestamp'],
            },
        ),
    ]
