# Generated by Django 5.0.2 on 2025-04-03 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_environmentrecord_inventoryadjustment_specialrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='单位：摄氏度', verbose_name='温度')),
                ('humidity', models.FloatField(help_text='单位：%', verbose_name='湿度')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '环境数据',
                'verbose_name_plural': '环境数据',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('shortage', '库存短缺'), ('excess', '库存过剩'), ('expiry', '临近过期'), ('damaged', '物品损坏'), ('miscount', '盘点差异'), ('special_request', '特殊出库请求'), ('other', '其他')], max_length=20, verbose_name='事件类型')),
                ('title', models.CharField(max_length=100, verbose_name='事件标题')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='解决方案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_events', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='events', to='inventory.ingredient', verbose_name='相关食材')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_events', to=settings.AUTH_USER_MODEL, verbose_name='报告人')),
            ],
            options={
                'verbose_name': '库存事件',
                'verbose_name_plural': '库存事件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', '日报'), ('weekly', '周报'), ('monthly', '月报'), ('custom', '自定义')], max_length=20, verbose_name='报告类型')),
                ('title', models.CharField(max_length=100, verbose_name='报告标题')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('details', models.TextField(verbose_name='详细内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '库存报告',
                'verbose_name_plural': '库存报告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='EnvironmentRecord',
        ),
        migrations.RemoveField(
            model_name='specialrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='specialrequest',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='specialrequest',
            name='requested_by',
        ),
        migrations.DeleteModel(
            name='InventoryAdjustment',
        ),
        migrations.DeleteModel(
            name='SpecialRequest',
        ),
    ]
