# Generated by Django 5.0.2 on 2025-04-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_environmentdata_inventoryevent_inventoryreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField(help_text='单位：%', verbose_name='湿度')),
                ('light', models.FloatField(help_text='单位：lux', verbose_name='光照')),
                ('timestamp', models.DateTimeField(verbose_name='时间戳')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '传感器数据',
                'verbose_name_plural': '传感器数据',
                'ordering': ['-timestamp'],
            },
        ),
    ]
