# Generated by Django 5.0.2 on 2025-04-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(blank=True, help_text='单位：摄氏度', null=True, verbose_name='温度'),
        ),
    ]
