# Generated by Django 5.0.2 on 2025-04-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True, verbose_name='解决方案说明'),
        ),
    ]
