# Generated by Django 5.0.2 on 2025-04-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_feedback_resolution_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='temperature_alert_threshold',
            field=models.FloatField(blank=True, help_text='温度超过此值时触发警报，单位：摄氏度', null=True, verbose_name='温度警报阈值'),
        ),
    ]
