# Generated by Django 5.0.2 on 2025-04-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_sensordata_temperature_alert_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='temperature_alert_threshold',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='threshold',
            field=models.FloatField(blank=True, help_text='单位：摄氏度，超过此值将触发警报', null=True, verbose_name='温度警报阈值'),
        ),
    ]
