# Generated by Django 5.0.2 on 2025-04-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_sensordata_temperature_alert_threshold_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-created_at'], 'verbose_name': '食材', 'verbose_name_plural': '食材'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(max_length=50, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
    ]
