# Generated by Django 5.0.2 on 2025-04-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_ingredient_options_alter_ingredient_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='过期日期'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='存放位置'),
        ),
    ]
