# Generated by Django 5.0.2 on 2025-04-05 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_ingredient_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperation',
            name='expiry_period',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='保质期'),
        ),
        migrations.AddField(
            model_name='inventoryoperation',
            name='inspector',
            field=models.ForeignKey(blank=True, help_text='入库操作的检收人员', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspected_operations', to=settings.AUTH_USER_MODEL, verbose_name='入库检收人员'),
        ),
        migrations.AddField(
            model_name='inventoryoperation',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='生产日期'),
        ),
    ]
