# Generated by Django 5.0.2 on 2025-04-05 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_category_materialrequest_materialrequestitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='指派时间'),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_material_requests', to=settings.AUTH_USER_MODEL, verbose_name='指派处理员工'),
        ),
    ]
