# Generated by Django 5.0.2 on 2025-04-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_materialrequest_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('check', '检查'), ('procurement', '采购'), ('inventory', '库存'), ('other', '其他')], default='other', max_length=20, verbose_name='任务类型'),
        ),
    ]
