# Generated by Django 5.0.2 on 2025-04-06 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperation',
            name='device_info',
            field=models.CharField(blank=True, help_text='进行操作的设备信息', max_length=255, null=True, verbose_name='设备信息'),
        ),
        migrations.AddField(
            model_name='inventoryoperation',
            name='ip_address',
            field=models.CharField(blank=True, help_text='操作时的IP地址', max_length=50, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='inventoryoperation',
            name='related_request',
            field=models.ForeignKey(blank=True, help_text='如果此操作由出库申请触发，记录关联的申请ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_operations', to='inventory.materialrequest', verbose_name='关联出库申请'),
        ),
        migrations.AddField(
            model_name='inventoryoperation',
            name='source',
            field=models.CharField(blank=True, help_text='操作的来源，如"管理员界面"、"普通用户界面"、"系统自动"等', max_length=50, null=True, verbose_name='操作来源'),
        ),
    ]
